services:
  database:
    image: mysql:8
    container_name: adj-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adjdemo
    ports:
      - "3307:3306"
    volumes:
      - adj-volume:/var/lib/mysql
    networks:
      - adj-net
    restart: unless-stopped

  backend: # Lo moví arriba para seguir la dependencia
    image: server:latest
    build:
      context: ./server  # <-- ¡CORRECCIÓN! Debe saber dónde construir la imagen
    environment:
      SERVER_PORT: 8080 # Puerto interno del contenedor (8081 en tu mapeo)
      DB_HOST: database # ¡CORRECTO! Usa el nombre del servicio
      DB_PORT: 3306     # Puerto interno estándar de MySQL
      DB_NAME: adjdemo
      DB_USER: root
      DB_PASS: root
    container_name: adj-server
    ports:
      - "8081:8080"
    networks:
      - adj-net
    depends_on:
      - database        # <-- ¡CORRECCIÓN! Backend depende de Database

  frontend:
    image: client:latest
    build:
      context: ./client
      args:
        API_HOST: localhost
        API_PORT: 8081
        API_BASE: /adj-api
    container_name: adj-client
    ports:
      - "3000:80"
    networks:
      - adj-net
    depends_on:
      - backend         # <-- ¡CORRECCIÓN! Frontend depende de Backend
#crear el volumen de la base de datos
volumes:
  adj-volume:
    external: true

#crear la red en la que trabajaran los contenedores
networks:
  adj-net:
    external: true